# Generated by Django 4.2.1 on 2023-10-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_category_womenmodel_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='womenmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_post', to='women.tagpost'),
        ),
    ]
