# Generated by Django 4.2.1 on 2023-12-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0011_womenmodel_photo_alter_womenmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womenmodel',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
